Issue 13
techworkersco/techworkersco.github.io pull request #137
Opened 2020-10-29 03:14 UTC by anaulin

2020-10-29 22:28 UTC, anaulin commented
Screenshot of what the issue looks like as of now:

![issue_13](https://user-images.githubusercontent.com/6729309/97639106-2731e880-19fb-11eb-8de1-b20b06cf5fc5.png)

@eddywashere I can't add you as a reviewer on the PR, but your review and comments is encouraged!

2020-10-30 03:54 UTC, stationaery requested changes
made minor edits, but otherwise, L!G!T!M!

2020-10-30 04:08 UTC, stationaery requested changes
too much cement!

2020-10-30 05:07 UTC, stationaery approved these changes

2020-10-30 05:33 UTC, eddywashere approved these changes

2020-10-30 14:20 UTC, merged